### ISSUE TITLE
Tooltips off by one day

### ISSUE THREAD

**Issue by milkmanjr** [SeiwonPark/react-contribution-calendar#5]
Tool tips on each cell for dates in 2024 are off by one.

**Screenshot**
![image](https://github.com/user-attachments/assets/b9019ef8-ff7b-4b75-8010-95b601806eb1)

**Comment by milkmanjr** [comment]
Looks like appending T00:00 to the date would fix it.

**Comment by milkmanjr** [comment]
Potential fix @ https://github.com/seiwonpark/react-contribution-calendar/pull/6

**Comment by seiwonpark** [comment]
resolved at #6
